// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TobacoBackend.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20250127000000_RemoveCategoriaId1Duplicate")]
    partial class RemoveCategoriaId1Duplicate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Este Designer.cs usa el mismo modelo que el snapshot actual
            // ya que el snapshot ya refleja el estado deseado (sin CategoriaId1)
            // El método Up() ejecuta SQL para eliminar la columna de la BD
        }
    }
}
